# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('image', models.ImageField(upload_to='project', verbose_name='Изображение')),
                ('created', models.DateField(auto_now_add=True)),
                ('meta_description', models.CharField(max_length=350)),
                ('content', djangocms_text_ckeditor.fields.HTMLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.CategoryProject', verbose_name='Категория')),
            ],
        ),
    ]
