# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproject',
            options={'verbose_name': 'Категория проекта', 'verbose_name_plural': 'Категории Проекта'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project', unique=True),
        ),
    ]
