# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180422_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproject',
            name='slug',
            field=models.SlugField(default='sd'),
        ),
    ]
